// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// AppointmentResults is the predicate function for appointmentresults builders.
type AppointmentResults func(*sql.Selector)

// BloodType is the predicate function for bloodtype builders.
type BloodType func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Diagnosis is the predicate function for diagnosis builders.
type Diagnosis func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Hospital is the predicate function for hospital builders.
type Hospital func(*sql.Selector)

// MedicalProcedure is the predicate function for medicalprocedure builders.
type MedicalProcedure func(*sql.Selector)

// MedicalRecord is the predicate function for medicalrecord builders.
type MedicalRecord func(*sql.Selector)

// Nurse is the predicate function for nurse builders.
type Nurse func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Prefix is the predicate function for prefix builders.
type Prefix func(*sql.Selector)

// ProcedureType is the predicate function for proceduretype builders.
type ProcedureType func(*sql.Selector)

// RightToTreatment is the predicate function for righttotreatment builders.
type RightToTreatment func(*sql.Selector)

// RightToTreatmentType is the predicate function for righttotreatmenttype builders.
type RightToTreatmentType func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// TreatmentType is the predicate function for treatmenttype builders.
type TreatmentType func(*sql.Selector)

// TriageResult is the predicate function for triageresult builders.
type TriageResult func(*sql.Selector)

// UrgencyLevel is the predicate function for urgencylevel builders.
type UrgencyLevel func(*sql.Selector)
