// Code generated by entc, DO NOT EDIT.

package hospital

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/team06/app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// HospitalName applies equality check predicate on the "HospitalName" field. It's identical to HospitalNameEQ.
func HospitalName(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHospitalName), v))
	})
}

// HospitalNameEQ applies the EQ predicate on the "HospitalName" field.
func HospitalNameEQ(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHospitalName), v))
	})
}

// HospitalNameNEQ applies the NEQ predicate on the "HospitalName" field.
func HospitalNameNEQ(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHospitalName), v))
	})
}

// HospitalNameIn applies the In predicate on the "HospitalName" field.
func HospitalNameIn(vs ...string) predicate.Hospital {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Hospital(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldHospitalName), v...))
	})
}

// HospitalNameNotIn applies the NotIn predicate on the "HospitalName" field.
func HospitalNameNotIn(vs ...string) predicate.Hospital {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Hospital(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldHospitalName), v...))
	})
}

// HospitalNameGT applies the GT predicate on the "HospitalName" field.
func HospitalNameGT(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHospitalName), v))
	})
}

// HospitalNameGTE applies the GTE predicate on the "HospitalName" field.
func HospitalNameGTE(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHospitalName), v))
	})
}

// HospitalNameLT applies the LT predicate on the "HospitalName" field.
func HospitalNameLT(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHospitalName), v))
	})
}

// HospitalNameLTE applies the LTE predicate on the "HospitalName" field.
func HospitalNameLTE(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHospitalName), v))
	})
}

// HospitalNameContains applies the Contains predicate on the "HospitalName" field.
func HospitalNameContains(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldHospitalName), v))
	})
}

// HospitalNameHasPrefix applies the HasPrefix predicate on the "HospitalName" field.
func HospitalNameHasPrefix(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldHospitalName), v))
	})
}

// HospitalNameHasSuffix applies the HasSuffix predicate on the "HospitalName" field.
func HospitalNameHasSuffix(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldHospitalName), v))
	})
}

// HospitalNameEqualFold applies the EqualFold predicate on the "HospitalName" field.
func HospitalNameEqualFold(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldHospitalName), v))
	})
}

// HospitalNameContainsFold applies the ContainsFold predicate on the "HospitalName" field.
func HospitalNameContainsFold(v string) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldHospitalName), v))
	})
}

// HasHospital applies the HasEdge predicate on the "hospital" edge.
func HasHospital() predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(HospitalTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HospitalTable, HospitalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHospitalWith applies the HasEdge predicate on the "hospital" edge with a given conditions (other predicates).
func HasHospitalWith(preds ...predicate.RightToTreatment) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(HospitalInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HospitalTable, HospitalColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Hospital) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Hospital) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Hospital) predicate.Hospital {
	return predicate.Hospital(func(s *sql.Selector) {
		p(s.Not())
	})
}
