// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/team06/app/ent/predicate"
	"github.com/team06/app/ent/righttotreatment"
	"github.com/team06/app/ent/righttotreatmenttype"
)

// RightToTreatmentTypeQuery is the builder for querying RightToTreatmentType entities.
type RightToTreatmentTypeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.RightToTreatmentType
	// eager-loading edges.
	withType *RightToTreatmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RightToTreatmentTypeQuery builder.
func (rtttq *RightToTreatmentTypeQuery) Where(ps ...predicate.RightToTreatmentType) *RightToTreatmentTypeQuery {
	rtttq.predicates = append(rtttq.predicates, ps...)
	return rtttq
}

// Limit adds a limit step to the query.
func (rtttq *RightToTreatmentTypeQuery) Limit(limit int) *RightToTreatmentTypeQuery {
	rtttq.limit = &limit
	return rtttq
}

// Offset adds an offset step to the query.
func (rtttq *RightToTreatmentTypeQuery) Offset(offset int) *RightToTreatmentTypeQuery {
	rtttq.offset = &offset
	return rtttq
}

// Order adds an order step to the query.
func (rtttq *RightToTreatmentTypeQuery) Order(o ...OrderFunc) *RightToTreatmentTypeQuery {
	rtttq.order = append(rtttq.order, o...)
	return rtttq
}

// QueryType chains the current query on the "type" edge.
func (rtttq *RightToTreatmentTypeQuery) QueryType() *RightToTreatmentQuery {
	query := &RightToTreatmentQuery{config: rtttq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rtttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rtttq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(righttotreatmenttype.Table, righttotreatmenttype.FieldID, selector),
			sqlgraph.To(righttotreatment.Table, righttotreatment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, righttotreatmenttype.TypeTable, righttotreatmenttype.TypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(rtttq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RightToTreatmentType entity from the query.
// Returns a *NotFoundError when no RightToTreatmentType was found.
func (rtttq *RightToTreatmentTypeQuery) First(ctx context.Context) (*RightToTreatmentType, error) {
	nodes, err := rtttq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{righttotreatmenttype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) FirstX(ctx context.Context) *RightToTreatmentType {
	node, err := rtttq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RightToTreatmentType ID from the query.
// Returns a *NotFoundError when no RightToTreatmentType ID was found.
func (rtttq *RightToTreatmentTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtttq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{righttotreatmenttype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := rtttq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RightToTreatmentType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one RightToTreatmentType entity is not found.
// Returns a *NotFoundError when no RightToTreatmentType entities are found.
func (rtttq *RightToTreatmentTypeQuery) Only(ctx context.Context) (*RightToTreatmentType, error) {
	nodes, err := rtttq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{righttotreatmenttype.Label}
	default:
		return nil, &NotSingularError{righttotreatmenttype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) OnlyX(ctx context.Context) *RightToTreatmentType {
	node, err := rtttq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RightToTreatmentType ID in the query.
// Returns a *NotSingularError when exactly one RightToTreatmentType ID is not found.
// Returns a *NotFoundError when no entities are found.
func (rtttq *RightToTreatmentTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtttq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = &NotSingularError{righttotreatmenttype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := rtttq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RightToTreatmentTypes.
func (rtttq *RightToTreatmentTypeQuery) All(ctx context.Context) ([]*RightToTreatmentType, error) {
	if err := rtttq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rtttq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) AllX(ctx context.Context) []*RightToTreatmentType {
	nodes, err := rtttq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RightToTreatmentType IDs.
func (rtttq *RightToTreatmentTypeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := rtttq.Select(righttotreatmenttype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := rtttq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rtttq *RightToTreatmentTypeQuery) Count(ctx context.Context) (int, error) {
	if err := rtttq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rtttq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) CountX(ctx context.Context) int {
	count, err := rtttq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rtttq *RightToTreatmentTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := rtttq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rtttq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rtttq *RightToTreatmentTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := rtttq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RightToTreatmentTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rtttq *RightToTreatmentTypeQuery) Clone() *RightToTreatmentTypeQuery {
	if rtttq == nil {
		return nil
	}
	return &RightToTreatmentTypeQuery{
		config:     rtttq.config,
		limit:      rtttq.limit,
		offset:     rtttq.offset,
		order:      append([]OrderFunc{}, rtttq.order...),
		predicates: append([]predicate.RightToTreatmentType{}, rtttq.predicates...),
		withType:   rtttq.withType.Clone(),
		// clone intermediate query.
		sql:  rtttq.sql.Clone(),
		path: rtttq.path,
	}
}

// WithType tells the query-builder to eager-load the nodes that are connected to
// the "type" edge. The optional arguments are used to configure the query builder of the edge.
func (rtttq *RightToTreatmentTypeQuery) WithType(opts ...func(*RightToTreatmentQuery)) *RightToTreatmentTypeQuery {
	query := &RightToTreatmentQuery{config: rtttq.config}
	for _, opt := range opts {
		opt(query)
	}
	rtttq.withType = query
	return rtttq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TypeName string `json:"TypeName,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RightToTreatmentType.Query().
//		GroupBy(righttotreatmenttype.FieldTypeName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (rtttq *RightToTreatmentTypeQuery) GroupBy(field string, fields ...string) *RightToTreatmentTypeGroupBy {
	group := &RightToTreatmentTypeGroupBy{config: rtttq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rtttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rtttq.sqlQuery(), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TypeName string `json:"TypeName,omitempty"`
//	}
//
//	client.RightToTreatmentType.Query().
//		Select(righttotreatmenttype.FieldTypeName).
//		Scan(ctx, &v)
//
func (rtttq *RightToTreatmentTypeQuery) Select(field string, fields ...string) *RightToTreatmentTypeSelect {
	rtttq.fields = append([]string{field}, fields...)
	return &RightToTreatmentTypeSelect{RightToTreatmentTypeQuery: rtttq}
}

func (rtttq *RightToTreatmentTypeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rtttq.fields {
		if !righttotreatmenttype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rtttq.path != nil {
		prev, err := rtttq.path(ctx)
		if err != nil {
			return err
		}
		rtttq.sql = prev
	}
	return nil
}

func (rtttq *RightToTreatmentTypeQuery) sqlAll(ctx context.Context) ([]*RightToTreatmentType, error) {
	var (
		nodes       = []*RightToTreatmentType{}
		_spec       = rtttq.querySpec()
		loadedTypes = [1]bool{
			rtttq.withType != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &RightToTreatmentType{config: rtttq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, rtttq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := rtttq.withType; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*RightToTreatmentType)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Type = []*RightToTreatment{}
		}
		query.withFKs = true
		query.Where(predicate.RightToTreatment(func(s *sql.Selector) {
			s.Where(sql.InValues(righttotreatmenttype.TypeColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.right_to_treatment_type_type
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "right_to_treatment_type_type" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "right_to_treatment_type_type" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Type = append(node.Edges.Type, n)
		}
	}

	return nodes, nil
}

func (rtttq *RightToTreatmentTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rtttq.querySpec()
	return sqlgraph.CountNodes(ctx, rtttq.driver, _spec)
}

func (rtttq *RightToTreatmentTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rtttq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (rtttq *RightToTreatmentTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   righttotreatmenttype.Table,
			Columns: righttotreatmenttype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: righttotreatmenttype.FieldID,
			},
		},
		From:   rtttq.sql,
		Unique: true,
	}
	if fields := rtttq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, righttotreatmenttype.FieldID)
		for i := range fields {
			if fields[i] != righttotreatmenttype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rtttq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rtttq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rtttq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rtttq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, righttotreatmenttype.ValidColumn)
			}
		}
	}
	return _spec
}

func (rtttq *RightToTreatmentTypeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(rtttq.driver.Dialect())
	t1 := builder.Table(righttotreatmenttype.Table)
	selector := builder.Select(t1.Columns(righttotreatmenttype.Columns...)...).From(t1)
	if rtttq.sql != nil {
		selector = rtttq.sql
		selector.Select(selector.Columns(righttotreatmenttype.Columns...)...)
	}
	for _, p := range rtttq.predicates {
		p(selector)
	}
	for _, p := range rtttq.order {
		p(selector, righttotreatmenttype.ValidColumn)
	}
	if offset := rtttq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rtttq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RightToTreatmentTypeGroupBy is the group-by builder for RightToTreatmentType entities.
type RightToTreatmentTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rtttgb *RightToTreatmentTypeGroupBy) Aggregate(fns ...AggregateFunc) *RightToTreatmentTypeGroupBy {
	rtttgb.fns = append(rtttgb.fns, fns...)
	return rtttgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rtttgb *RightToTreatmentTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rtttgb.path(ctx)
	if err != nil {
		return err
	}
	rtttgb.sql = query
	return rtttgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := rtttgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(rtttgb.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := rtttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := rtttgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rtttgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) StringX(ctx context.Context) string {
	v, err := rtttgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(rtttgb.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := rtttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := rtttgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rtttgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) IntX(ctx context.Context) int {
	v, err := rtttgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(rtttgb.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := rtttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := rtttgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rtttgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := rtttgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(rtttgb.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := rtttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := rtttgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (rtttgb *RightToTreatmentTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rtttgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rtttgb *RightToTreatmentTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := rtttgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rtttgb *RightToTreatmentTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rtttgb.fields {
		if !righttotreatmenttype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rtttgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rtttgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rtttgb *RightToTreatmentTypeGroupBy) sqlQuery() *sql.Selector {
	selector := rtttgb.sql
	columns := make([]string, 0, len(rtttgb.fields)+len(rtttgb.fns))
	columns = append(columns, rtttgb.fields...)
	for _, fn := range rtttgb.fns {
		columns = append(columns, fn(selector, righttotreatmenttype.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(rtttgb.fields...)
}

// RightToTreatmentTypeSelect is the builder for selecting fields of RightToTreatmentType entities.
type RightToTreatmentTypeSelect struct {
	*RightToTreatmentTypeQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rttts *RightToTreatmentTypeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rttts.prepareQuery(ctx); err != nil {
		return err
	}
	rttts.sql = rttts.RightToTreatmentTypeQuery.sqlQuery()
	return rttts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := rttts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(rttts.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := rttts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) StringsX(ctx context.Context) []string {
	v, err := rttts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = rttts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) StringX(ctx context.Context) string {
	v, err := rttts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(rttts.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := rttts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) IntsX(ctx context.Context) []int {
	v, err := rttts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = rttts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) IntX(ctx context.Context) int {
	v, err := rttts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(rttts.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := rttts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := rttts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = rttts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := rttts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(rttts.fields) > 1 {
		return nil, errors.New("ent: RightToTreatmentTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := rttts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := rttts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (rttts *RightToTreatmentTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = rttts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{righttotreatmenttype.Label}
	default:
		err = fmt.Errorf("ent: RightToTreatmentTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (rttts *RightToTreatmentTypeSelect) BoolX(ctx context.Context) bool {
	v, err := rttts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rttts *RightToTreatmentTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rttts.sqlQuery().Query()
	if err := rttts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rttts *RightToTreatmentTypeSelect) sqlQuery() sql.Querier {
	selector := rttts.sql
	selector.Select(selector.Columns(rttts.fields...)...)
	return selector
}
