// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/team06/app/ent/predicate"
	"github.com/team06/app/ent/righttotreatmenttype"
)

// RightToTreatmentTypeDelete is the builder for deleting a RightToTreatmentType entity.
type RightToTreatmentTypeDelete struct {
	config
	hooks    []Hook
	mutation *RightToTreatmentTypeMutation
}

// Where adds a new predicate to the RightToTreatmentTypeDelete builder.
func (rtttd *RightToTreatmentTypeDelete) Where(ps ...predicate.RightToTreatmentType) *RightToTreatmentTypeDelete {
	rtttd.mutation.predicates = append(rtttd.mutation.predicates, ps...)
	return rtttd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rtttd *RightToTreatmentTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rtttd.hooks) == 0 {
		affected, err = rtttd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RightToTreatmentTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rtttd.mutation = mutation
			affected, err = rtttd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rtttd.hooks) - 1; i >= 0; i-- {
			mut = rtttd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rtttd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtttd *RightToTreatmentTypeDelete) ExecX(ctx context.Context) int {
	n, err := rtttd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rtttd *RightToTreatmentTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: righttotreatmenttype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: righttotreatmenttype.FieldID,
			},
		},
	}
	if ps := rtttd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rtttd.driver, _spec)
}

// RightToTreatmentTypeDeleteOne is the builder for deleting a single RightToTreatmentType entity.
type RightToTreatmentTypeDeleteOne struct {
	rtttd *RightToTreatmentTypeDelete
}

// Exec executes the deletion query.
func (rtttdo *RightToTreatmentTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := rtttdo.rtttd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{righttotreatmenttype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rtttdo *RightToTreatmentTypeDeleteOne) ExecX(ctx context.Context) {
	rtttdo.rtttd.ExecX(ctx)
}
