// Code generated by entc, DO NOT EDIT.

package nurse

const (
	// Label holds the string label denoting the nurse type in the database.
	Label = "nurse"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNurseName holds the string denoting the nursename field in the database.
	FieldNurseName = "nurse_name"
	// FieldNurseUsername holds the string denoting the nurseusername field in the database.
	FieldNurseUsername = "nurse_username"
	// FieldNursePassword holds the string denoting the nursepassword field in the database.
	FieldNursePassword = "nurse_password"

	// EdgeNurseToTriageResult holds the string denoting the nursetotriageresult edge name in mutations.
	EdgeNurseToTriageResult = "nurseToTriageResult"
	// EdgeNurseToAppointmentResults holds the string denoting the nursetoappointmentresults edge name in mutations.
	EdgeNurseToAppointmentResults = "NurseToAppointmentResults"

	// Table holds the table name of the nurse in the database.
	Table = "nurses"
	// NurseToTriageResultTable is the table the holds the nurseToTriageResult relation/edge.
	NurseToTriageResultTable = "triage_results"
	// NurseToTriageResultInverseTable is the table name for the TriageResult entity.
	// It exists in this package in order to avoid circular dependency with the "triageresult" package.
	NurseToTriageResultInverseTable = "triage_results"
	// NurseToTriageResultColumn is the table column denoting the nurseToTriageResult relation/edge.
	NurseToTriageResultColumn = "nurse_nurse_to_triage_result"
	// NurseToAppointmentResultsTable is the table the holds the NurseToAppointmentResults relation/edge.
	NurseToAppointmentResultsTable = "appointment_results"
	// NurseToAppointmentResultsInverseTable is the table name for the AppointmentResults entity.
	// It exists in this package in order to avoid circular dependency with the "appointmentresults" package.
	NurseToAppointmentResultsInverseTable = "appointment_results"
	// NurseToAppointmentResultsColumn is the table column denoting the NurseToAppointmentResults relation/edge.
	NurseToAppointmentResultsColumn = "nurse_nurse_to_appointment_results"
)

// Columns holds all SQL columns for nurse fields.
var Columns = []string{
	FieldID,
	FieldNurseName,
	FieldNurseUsername,
	FieldNursePassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NurseNameValidator is a validator for the "nurseName" field. It is called by the builders before save.
	NurseNameValidator func(string) error
	// NurseUsernameValidator is a validator for the "nurseUsername" field. It is called by the builders before save.
	NurseUsernameValidator func(string) error
	// NursePasswordValidator is a validator for the "nursePassword" field. It is called by the builders before save.
	NursePasswordValidator func(string) error
)
