/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAppointmentResultsEdges,
    EntAppointmentResultsEdgesFromJSON,
    EntAppointmentResultsEdgesFromJSONTyped,
    EntAppointmentResultsEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAppointmentResults
 */
export interface EntAppointmentResults {
    /**
     * AddtimeSave holds the value of the "addtimeSave" field.
     * @type {string}
     * @memberof EntAppointmentResults
     */
    addtimeSave?: string;
    /**
     * Advice holds the value of the "advice" field.
     * @type {string}
     * @memberof EntAppointmentResults
     */
    advice?: string;
    /**
     * CauseAppoint holds the value of the "causeAppoint" field.
     * @type {string}
     * @memberof EntAppointmentResults
     */
    causeAppoint?: string;
    /**
     * DateAppoint holds the value of the "dateAppoint" field.
     * @type {string}
     * @memberof EntAppointmentResults
     */
    dateAppoint?: string;
    /**
     * 
     * @type {EntAppointmentResultsEdges}
     * @memberof EntAppointmentResults
     */
    edges?: EntAppointmentResultsEdges;
    /**
     * HourBeforeAppoint holds the value of the "hourBeforeAppoint" field.
     * @type {number}
     * @memberof EntAppointmentResults
     */
    hourBeforeAppoint?: number;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntAppointmentResults
     */
    id?: number;
    /**
     * MinuteBeforeAppoint holds the value of the "minuteBeforeAppoint" field.
     * @type {number}
     * @memberof EntAppointmentResults
     */
    minuteBeforeAppoint?: number;
    /**
     * TimeAppoint holds the value of the "timeAppoint" field.
     * @type {string}
     * @memberof EntAppointmentResults
     */
    timeAppoint?: string;
}

export function EntAppointmentResultsFromJSON(json: any): EntAppointmentResults {
    return EntAppointmentResultsFromJSONTyped(json, false);
}

export function EntAppointmentResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAppointmentResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addtimeSave': !exists(json, 'addtimeSave') ? undefined : json['addtimeSave'],
        'advice': !exists(json, 'advice') ? undefined : json['advice'],
        'causeAppoint': !exists(json, 'causeAppoint') ? undefined : json['causeAppoint'],
        'dateAppoint': !exists(json, 'dateAppoint') ? undefined : json['dateAppoint'],
        'edges': !exists(json, 'edges') ? undefined : EntAppointmentResultsEdgesFromJSON(json['edges']),
        'hourBeforeAppoint': !exists(json, 'hourBeforeAppoint') ? undefined : json['hourBeforeAppoint'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'minuteBeforeAppoint': !exists(json, 'minuteBeforeAppoint') ? undefined : json['minuteBeforeAppoint'],
        'timeAppoint': !exists(json, 'timeAppoint') ? undefined : json['timeAppoint'],
    };
}

export function EntAppointmentResultsToJSON(value?: EntAppointmentResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addtimeSave': value.addtimeSave,
        'advice': value.advice,
        'causeAppoint': value.causeAppoint,
        'dateAppoint': value.dateAppoint,
        'edges': EntAppointmentResultsEdgesToJSON(value.edges),
        'hourBeforeAppoint': value.hourBeforeAppoint,
        'id': value.id,
        'minuteBeforeAppoint': value.minuteBeforeAppoint,
        'timeAppoint': value.timeAppoint,
    };
}


