/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntNurse,
    EntNurseFromJSON,
    EntNurseFromJSONTyped,
    EntNurseToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntRoom,
    EntRoomFromJSON,
    EntRoomFromJSONTyped,
    EntRoomToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAppointmentResultsEdges
 */
export interface EntAppointmentResultsEdges {
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntAppointmentResultsEdges
     */
    appointmentResultsToDoctor?: EntDoctor;
    /**
     * 
     * @type {EntNurse}
     * @memberof EntAppointmentResultsEdges
     */
    appointmentResultsToNurse?: EntNurse;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntAppointmentResultsEdges
     */
    appointmentResultsToPatient?: EntPatient;
    /**
     * 
     * @type {EntRoom}
     * @memberof EntAppointmentResultsEdges
     */
    appointmentResultsToRoom?: EntRoom;
}

export function EntAppointmentResultsEdgesFromJSON(json: any): EntAppointmentResultsEdges {
    return EntAppointmentResultsEdgesFromJSONTyped(json, false);
}

export function EntAppointmentResultsEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAppointmentResultsEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appointmentResultsToDoctor': !exists(json, 'appointmentResultsToDoctor') ? undefined : EntDoctorFromJSON(json['appointmentResultsToDoctor']),
        'appointmentResultsToNurse': !exists(json, 'appointmentResultsToNurse') ? undefined : EntNurseFromJSON(json['appointmentResultsToNurse']),
        'appointmentResultsToPatient': !exists(json, 'appointmentResultsToPatient') ? undefined : EntPatientFromJSON(json['appointmentResultsToPatient']),
        'appointmentResultsToRoom': !exists(json, 'appointmentResultsToRoom') ? undefined : EntRoomFromJSON(json['appointmentResultsToRoom']),
    };
}

export function EntAppointmentResultsEdgesToJSON(value?: EntAppointmentResultsEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appointmentResultsToDoctor': EntDoctorToJSON(value.appointmentResultsToDoctor),
        'appointmentResultsToNurse': EntNurseToJSON(value.appointmentResultsToNurse),
        'appointmentResultsToPatient': EntPatientToJSON(value.appointmentResultsToPatient),
        'appointmentResultsToRoom': EntRoomToJSON(value.appointmentResultsToRoom),
    };
}


