/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientDetail,
    EntPatientDetailFromJSON,
    EntPatientDetailFromJSONTyped,
    EntPatientDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntGenderEdges
 */
export interface EntGenderEdges {
    /**
     * PatientDetails holds the value of the patient_details edge.
     * @type {Array<EntPatientDetail>}
     * @memberof EntGenderEdges
     */
    patientDetails?: Array<EntPatientDetail>;
}

export function EntGenderEdgesFromJSON(json: any): EntGenderEdges {
    return EntGenderEdgesFromJSONTyped(json, false);
}

export function EntGenderEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntGenderEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientDetails': !exists(json, 'patientDetails') ? undefined : ((json['patientDetails'] as Array<any>).map(EntPatientDetailFromJSON)),
    };
}

export function EntGenderEdgesToJSON(value?: EntGenderEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientDetails': value.patientDetails === undefined ? undefined : ((value.patientDetails as Array<any>).map(EntPatientDetailToJSON)),
    };
}


