/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRightToTreatment,
    EntRightToTreatmentFromJSON,
    EntRightToTreatmentFromJSONTyped,
    EntRightToTreatmentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntHospitalEdges
 */
export interface EntHospitalEdges {
    /**
     * Hospital holds the value of the hospital edge.
     * @type {Array<EntRightToTreatment>}
     * @memberof EntHospitalEdges
     */
    hospital?: Array<EntRightToTreatment>;
}

export function EntHospitalEdgesFromJSON(json: any): EntHospitalEdges {
    return EntHospitalEdgesFromJSONTyped(json, false);
}

export function EntHospitalEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntHospitalEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hospital': !exists(json, 'hospital') ? undefined : ((json['hospital'] as Array<any>).map(EntRightToTreatmentFromJSON)),
    };
}

export function EntHospitalEdgesToJSON(value?: EntHospitalEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hospital': value.hospital === undefined ? undefined : ((value.hospital as Array<any>).map(EntRightToTreatmentToJSON)),
    };
}


