/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntProcedureType,
    EntProcedureTypeFromJSON,
    EntProcedureTypeFromJSONTyped,
    EntProcedureTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMedicalProcedureEdges
 */
export interface EntMedicalProcedureEdges {
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntMedicalProcedureEdges
     */
    doctor?: EntDoctor;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntMedicalProcedureEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntProcedureType}
     * @memberof EntMedicalProcedureEdges
     */
    procedureType?: EntProcedureType;
}

export function EntMedicalProcedureEdgesFromJSON(json: any): EntMedicalProcedureEdges {
    return EntMedicalProcedureEdgesFromJSONTyped(json, false);
}

export function EntMedicalProcedureEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMedicalProcedureEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctor': !exists(json, 'doctor') ? undefined : EntDoctorFromJSON(json['doctor']),
        'patient': !exists(json, 'patient') ? undefined : EntPatientFromJSON(json['patient']),
        'procedureType': !exists(json, 'procedureType') ? undefined : EntProcedureTypeFromJSON(json['procedureType']),
    };
}

export function EntMedicalProcedureEdgesToJSON(value?: EntMedicalProcedureEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor': EntDoctorToJSON(value.doctor),
        'patient': EntPatientToJSON(value.patient),
        'procedureType': EntProcedureTypeToJSON(value.procedureType),
    };
}


