/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntAppointmentResults,
    EntAppointmentResultsFromJSON,
    EntAppointmentResultsFromJSONTyped,
    EntAppointmentResultsToJSON,
    EntTriageResult,
    EntTriageResultFromJSON,
    EntTriageResultFromJSONTyped,
    EntTriageResultToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntNurseEdges
 */
export interface EntNurseEdges {
    /**
     * NurseToAppointmentResults holds the value of the NurseToAppointmentResults edge.
     * @type {Array<EntAppointmentResults>}
     * @memberof EntNurseEdges
     */
    nurseToAppointmentResults?: Array<EntAppointmentResults>;
    /**
     * TriageResult holds the value of the triageResult edge.
     * @type {Array<EntTriageResult>}
     * @memberof EntNurseEdges
     */
    triageResult?: Array<EntTriageResult>;
}

export function EntNurseEdgesFromJSON(json: any): EntNurseEdges {
    return EntNurseEdgesFromJSONTyped(json, false);
}

export function EntNurseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntNurseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nurseToAppointmentResults': !exists(json, 'nurseToAppointmentResults') ? undefined : ((json['nurseToAppointmentResults'] as Array<any>).map(EntAppointmentResultsFromJSON)),
        'triageResult': !exists(json, 'triageResult') ? undefined : ((json['triageResult'] as Array<any>).map(EntTriageResultFromJSON)),
    };
}

export function EntNurseEdgesToJSON(value?: EntNurseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nurseToAppointmentResults': value.nurseToAppointmentResults === undefined ? undefined : ((value.nurseToAppointmentResults as Array<any>).map(EntAppointmentResultsToJSON)),
        'triageResult': value.triageResult === undefined ? undefined : ((value.triageResult as Array<any>).map(EntTriageResultToJSON)),
    };
}


