/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientDetailEdges,
    EntPatientDetailEdgesFromJSON,
    EntPatientDetailEdgesFromJSONTyped,
    EntPatientDetailEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientDetail
 */
export interface EntPatientDetail {
    /**
     * 
     * @type {EntPatientDetailEdges}
     * @memberof EntPatientDetail
     */
    edges?: EntPatientDetailEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPatientDetail
     */
    id?: number;
}

export function EntPatientDetailFromJSON(json: any): EntPatientDetail {
    return EntPatientDetailFromJSONTyped(json, false);
}

export function EntPatientDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntPatientDetailEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPatientDetailToJSON(value?: EntPatientDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntPatientDetailEdgesToJSON(value.edges),
        'id': value.id,
    };
}


