/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDepartment,
    EntDepartmentFromJSON,
    EntDepartmentFromJSONTyped,
    EntDepartmentToJSON,
    EntNurse,
    EntNurseFromJSON,
    EntNurseFromJSONTyped,
    EntNurseToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntUrgencyLevel,
    EntUrgencyLevelFromJSON,
    EntUrgencyLevelFromJSONTyped,
    EntUrgencyLevelToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTriageResultEdges
 */
export interface EntTriageResultEdges {
    /**
     * 
     * @type {EntDepartment}
     * @memberof EntTriageResultEdges
     */
    department?: EntDepartment;
    /**
     * 
     * @type {EntNurse}
     * @memberof EntTriageResultEdges
     */
    nurse?: EntNurse;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntTriageResultEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntUrgencyLevel}
     * @memberof EntTriageResultEdges
     */
    urgencyLevel?: EntUrgencyLevel;
}

export function EntTriageResultEdgesFromJSON(json: any): EntTriageResultEdges {
    return EntTriageResultEdgesFromJSONTyped(json, false);
}

export function EntTriageResultEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTriageResultEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'Department') ? undefined : EntDepartmentFromJSON(json['Department']),
        'nurse': !exists(json, 'Nurse') ? undefined : EntNurseFromJSON(json['Nurse']),
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
        'urgencyLevel': !exists(json, 'UrgencyLevel') ? undefined : EntUrgencyLevelFromJSON(json['UrgencyLevel']),
    };
}

export function EntTriageResultEdgesToJSON(value?: EntTriageResultEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': EntDepartmentToJSON(value.department),
        'nurse': EntNurseToJSON(value.nurse),
        'patient': EntPatientToJSON(value.patient),
        'urgencyLevel': EntUrgencyLevelToJSON(value.urgencyLevel),
    };
}


