/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTriageResult,
    EntTriageResultFromJSON,
    EntTriageResultFromJSONTyped,
    EntTriageResultToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUrgencyLevelEdges
 */
export interface EntUrgencyLevelEdges {
    /**
     * TriageResult holds the value of the triageResult edge.
     * @type {Array<EntTriageResult>}
     * @memberof EntUrgencyLevelEdges
     */
    triageResult?: Array<EntTriageResult>;
}

export function EntUrgencyLevelEdgesFromJSON(json: any): EntUrgencyLevelEdges {
    return EntUrgencyLevelEdgesFromJSONTyped(json, false);
}

export function EntUrgencyLevelEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUrgencyLevelEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'triageResult': !exists(json, 'triageResult') ? undefined : ((json['triageResult'] as Array<any>).map(EntTriageResultFromJSON)),
    };
}

export function EntUrgencyLevelEdgesToJSON(value?: EntUrgencyLevelEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'triageResult': value.triageResult === undefined ? undefined : ((value.triageResult as Array<any>).map(EntTriageResultToJSON)),
    };
}


